// What a Sync does with a file that changed on both sides: a second copy, or one question (ADR-0046).
//
// ─────────────────────────────────────────────────────────────────────────────────────────────
// BOTH VERSIONS SURVIVE, AND NEITHER IS MERGED
//
// Ballastella will not combine two GeoJSON annotation sets or two Alignments of one sheet: the
// result is a document neither scholar wrote (ADR-0014). What it does instead is make sure the
// scholar can *look* at both, and then delete one — which is a scholarly judgement and theirs.
//
// So a Conflict is resolved by preserving the Remote's version beside the author's, at a path of its
// own, and letting the author's version stand where it was. The Baseline then advances at the
// contested path to the Remote's blob: this Workspace has now taken GitHub's version in, so what is
// left is an ordinary *outbound* change, and the next send puts the author's copy and the second copy
// on the Remote together. That is what makes both machines end up looking at the same pair.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────
// AT THE COARSEST CONTESTED UNIT, AND THAT IS THE RULE THAT KEEPS IT READABLE
//
//   `<project>/annotations/<layer>.geojson`  → another Layer in that Project, `(from GitHub)`
//   `<project>/project.json`                 → another Project directory, `(from GitHub)`, off the
//                                              Front Page — and its Layers do **not** also double
//   `alignments/<image>.json`                → nothing at all; the author is asked which to keep
//
// A Project with three contested Layers and a contested manifest would otherwise yield a duplicate
// Project *and* three duplicate Layers, and the scholar would have six things to read where two
// would have done.
//
// ⚠ **The Alignment is the exception and the exception is the point.** There is exactly one
// Alignment per Map Image, keyed by the image's id (ADR-0023), so a second file at
// `alignments/<image-id> (from GitHub).json` is referenced by nothing and drawn nowhere. A copy the
// scholar cannot look at is worse than a question, so the question is asked instead — with each
// side's Control Point count and date, which is everything needed to answer it without opening both.
//
// ⚠ **Tiles and the site record are not here because they cannot be contested.** `images/**` and
// `base-map/tiles/**` are written once at ingest and never edited; `ballastella-site.json` is
// regenerated by every Sync. Anything else that somehow arrives contested is left exactly as it is
// on both sides rather than given an invented rule.

import { alignmentImageId, type Alignment } from '../alignment/alignment.js';
import { parseAlignment } from '../alignment/georeference-annotation.js';
import {
	ANNOTATION_DIRECTORY,
	addLayer,
	annotationPath,
	moveLayer,
	newAnnotationLayer,
	type Layer
} from '../project/layer.js';
import {
	PROJECT_FILE_NAME,
	parseProjectFile,
	projectFilePath,
	serialiseProjectFile
} from '../project/project-file.js';
import { foldName, takenDirectoryNames, unusedDirectoryName } from '../project/workspace.js';
import { createHttpProjectStore } from '../store/http-project-store.js';
import type { Bytes, ProjectStore, StorePath } from '../store/project-store.js';
import { GITHUB_RAW_ORIGIN } from './github-api.js';
import { readRemoteCommitDate, urlPath } from './remote-tree.js';
import { recognisedProjectDirectories } from './synchronization-paths.js';
import type { FetchFn } from '../injection/store-image-fetch.js';
import type { RemoteRelationship } from './synchronization-metadata.js';
import type { SourcePath } from './synchronization-planner.js';

/**
 * What a Conflict Copy is called, appended to whatever the contested thing was called.
 *
 * ⚠ **Not the machine, the author, or a timestamp** (ADR-0046). Which laptop wrote it is not a fact
 * either side can state about the other, and a timestamp is a fact about a clock. *From GitHub* is
 * the one description that is true read from either end of the pair.
 */
export const CONFLICT_COPY_SUFFIX = '(from GitHub)';

/** `Canals` → `Canals (from GitHub)`. */
export const conflictCopyName = (name: string): string => `${name} ${CONFLICT_COPY_SUFFIX}`;

/** A Project whose manifest is contested: the whole Project doubles. */
export interface ContestedProject {
	readonly directory: string;
	/** `<directory>/project.json`. */
	readonly path: string;
}

/** An Annotation Layer whose GeoJSON is contested, in a Project whose manifest is not. */
export interface ContestedLayer {
	readonly project: string;
	readonly layerId: string;
	/** `<project>/annotations/<layerId>.geojson`. */
	readonly path: string;
}

/** A Map Image whose Alignment is contested: no copy, a question. */
export interface ContestedAlignment {
	readonly imageId: string;
	/** `alignments/<imageId>.json`. */
	readonly path: string;
}

/** Every contested path, sorted into the thing its resolution is about. */
export interface ContestedThings {
	readonly projects: readonly ContestedProject[];
	readonly layers: readonly ContestedLayer[];
	readonly alignments: readonly ContestedAlignment[];
	/** Contested paths no rule covers, left exactly as they are on both sides. */
	readonly other: readonly string[];
}

const GEOJSON_SUFFIX = '.geojson';

/**
 * Sort contested paths into the three kinds that have a resolution, and the rest.
 *
 * Pure, and the coarsest-unit rule lives here: a Layer inside a Project whose manifest is contested
 * is **not** a {@link ContestedLayer}, because the duplicate Project already carries the Remote's
 * version of it.
 */
export function classifyConflicts(paths: Iterable<string>): ContestedThings {
	const contested = [...paths].sort();
	const projects: ContestedProject[] = [];
	const layers: ContestedLayer[] = [];
	const alignments: ContestedAlignment[] = [];
	const other: string[] = [];

	const doubled = new Set<string>();
	for (const path of contested) {
		const segments = path.split('/');
		if (segments.length === 2 && segments[1] === PROJECT_FILE_NAME) {
			doubled.add(segments[0] as string);
			projects.push({ directory: segments[0] as string, path });
		}
	}

	for (const path of contested) {
		const imageId = alignmentImageId(path);
		if (imageId !== null) {
			alignments.push({ imageId, path });
			continue;
		}
		const segments = path.split('/');
		const [directory, annotations, file] = segments;
		// Covered by the duplicate Project, whichever of its files it is — the coarsest-unit rule.
		if (directory !== undefined && doubled.has(directory)) continue;
		if (
			segments.length === 3 &&
			annotations === ANNOTATION_DIRECTORY &&
			file !== undefined &&
			file.endsWith(GEOJSON_SUFFIX) &&
			file.length > GEOJSON_SUFFIX.length &&
			directory !== undefined
		) {
			layers.push({
				project: directory,
				layerId: file.slice(0, -GEOJSON_SUFFIX.length),
				path
			});
			continue;
		}
		other.push(path);
	}

	return { projects, layers, alignments, other };
}

/** One file a Conflict Copy puts into the Workspace. */
export interface ConflictCopyFile {
	readonly path: string;
	readonly bytes: Bytes;
	/** `replace` only ever the manifest of a Project gaining a Layer; every copy itself is new. */
	readonly effect: 'add' | 'replace';
}

/** One Conflict Copy, in the terms the author reads it in. */
export type ConflictCopy =
	| {
			readonly kind: 'layer';
			/** The contested path whose Remote version this preserves. */
			readonly contested: string;
			readonly project: string;
			readonly name: string;
			readonly path: string;
	  }
	| {
			readonly kind: 'project';
			readonly contested: string;
			readonly name: string;
			readonly directory: string;
	  };

/** What resolving this Sync's Conflicts came to. */
export interface ConflictResolution {
	/** What was made, for the report a scholar reads. */
	readonly copies: readonly ConflictCopy[];
	/** The files to write, sorted by path. */
	readonly files: readonly ConflictCopyFile[];
	/**
	 * Contested paths whose Baseline entry may advance to the Remote's blob, sorted.
	 *
	 * ⚠ **Because the Remote's version is now *here*.** Advancing is what turns the contested row
	 * into an ordinary `outbound` one, so the author's own copy is what the next send puts at that
	 * path — the two sides then agree, and both hold the pair.
	 */
	readonly settled: readonly string[];
	/** Contested Alignments, which are a question rather than a copy. */
	readonly alignments: readonly ContestedAlignment[];
	/** Contested paths no rule covers. Still contested afterwards, on both sides. */
	readonly unresolved: readonly string[];
}

export interface ResolveConflictsOptions {
	/** The plan's contested rows. */
	readonly conflicts: readonly SourcePath[];
	/** Every path the Remote holds, for the Project directories a duplicate has to copy. */
	readonly remote: Iterable<string>;
	/** Every path this Workspace holds, so a duplicate's directory is one nothing occupies. */
	readonly local: Iterable<string>;
	/** Every path the Baseline records, which reserves directories neither live side shows. */
	readonly baseline?: Iterable<string>;
	/** The Remote's bytes at a path, checked against the blob SHA its tree listing named. */
	readonly readRemote: (path: string) => Promise<Bytes>;
	/**
	 * A `project.json`'s bytes as this get will leave them, before any copy.
	 *
	 * ⚠ **Prospective and not local.** A Project can have an inbound manifest and a contested Layer at
	 * once, and adding the copy's Layer to the *local* manifest would then be overwritten by the
	 * inbound one — the Layer would be gone and its GeoJSON left behind as an orphan.
	 */
	readonly readManifest: (path: string) => Promise<Bytes>;
	/** The fresh Layer id a copy takes. Injected so a test's copy has a predictable path. */
	readonly mintLayerId?: () => string;
}

/**
 * Work out the Conflict Copies this Sync makes, and the bytes they are made of.
 *
 * Nothing is written here: the caller puts {@link ConflictResolution.files} through its own
 * transaction, so a Conflict Copy arrives under the same crash-recovery protocol as everything else
 * a get brings in.
 */
export async function resolveConflicts(
	options: ResolveConflictsOptions
): Promise<ConflictResolution> {
	// ⚠ **A path the Remote no longer holds has no version to copy.** "Deleted there, changed here" is
	// a Conflict under the three-way table and its resolution is that the author's work stays exactly
	// where it is: there is nothing to preserve beside it, and nothing is removed.
	const contested = classifyConflicts(
		options.conflicts.filter((row) => row.remote !== null).map((row) => row.path)
	);
	const mintLayerId = options.mintLayerId ?? ((): string => crypto.randomUUID());
	const remote = [...options.remote];

	const copies: ConflictCopy[] = [];
	const files: ConflictCopyFile[] = [];
	const settled: string[] = [];

	// ── A contested manifest doubles the whole Project ────────────────────────────────────────
	const taken = takenDirectoryNames(options.local);
	for (const directory of recognisedProjectDirectories({
		remote,
		baseline: [...(options.baseline ?? [])]
	})) {
		taken.add(foldName(directory));
	}

	const contestedPaths = new Set(contested.projects.map((project) => project.path));
	for (const row of options.conflicts) contestedPaths.add(row.path);

	for (const project of contested.projects) {
		const manifest = parseProjectFile(await options.readRemote(project.path));
		const name = conflictCopyName(manifest.name);
		const directory = unusedDirectoryName(name, taken);
		taken.add(foldName(directory));

		for (const path of remote) {
			if (!path.startsWith(`${project.directory}/`)) continue;
			const destination = `${directory}/${path.slice(project.directory.length + 1)}`;
			files.push({
				path: destination,
				bytes:
					path === project.path
						? // ⚠ **Off the Front Page**, because a duplicate arriving on a public site is a
							// decision nobody took: the author has not yet chosen which of the two to keep.
							serialiseProjectFile({ ...manifest, name, onFrontPage: false })
						: await options.readRemote(path),
				effect: 'add'
			});
			// ⚠ **Only the contested paths advance.** Every file of the Project is copied, because the
			// duplicate has to be a whole Project; a Baseline entry advanced for an *uncontested* one
			// would claim this Workspace had taken in a change nobody made.
			if (contestedPaths.has(path)) settled.push(path);
		}
		settled.push(project.path);
		copies.push({ kind: 'project', contested: project.path, name, directory });
	}

	// ── A contested Annotation becomes another Layer in the same Project ──────────────────────
	const byProject = new Map<string, ContestedLayer[]>();
	for (const layer of contested.layers) {
		const held = byProject.get(layer.project);
		if (held === undefined) byProject.set(layer.project, [layer]);
		else held.push(layer);
	}

	for (const [directory, contestedLayers] of [...byProject].sort(([a], [b]) => (a < b ? -1 : 1))) {
		const path = projectFilePath(directory);
		const manifest = parseProjectFile(await options.readManifest(path));
		let layers = manifest.layers;
		for (const contestedLayer of contestedLayers) {
			const original = layers.find((layer) => layer.id === contestedLayer.layerId);
			const copy = newAnnotationLayer({
				id: mintLayerId(),
				name: conflictCopyName(original?.name ?? contestedLayer.layerId)
			});
			layers = beside(addLayer(layers, copy), copy.id, original?.id);
			files.push({
				path: `${directory}/${annotationPath(copy.id)}`,
				bytes: await options.readRemote(contestedLayer.path),
				effect: 'add'
			});
			settled.push(contestedLayer.path);
			copies.push({
				kind: 'layer',
				contested: contestedLayer.path,
				project: directory,
				name: copy.name,
				path: `${directory}/${annotationPath(copy.id)}`
			});
		}
		files.push({
			path,
			bytes: serialiseProjectFile({ ...manifest, layers }),
			// The one `replace` there is: the Project's own manifest, gaining the copies' Layers.
			effect: 'replace'
		});
	}

	return {
		copies,
		files: [...files].sort((left, right) => (left.path < right.path ? -1 : 1)),
		settled: settled.sort(),
		alignments: contested.alignments,
		unresolved: contested.other
	};
}

/**
 * Put the freshly added Layer immediately under the one it is a copy of.
 *
 * `addLayer` puts a new Layer at the top of the stack, which is right for a Layer the author just
 * made and wrong for this one: a copy the scholar is being asked to compare against its original
 * belongs beside it, not above four unrelated Layers.
 */
function beside(
	layers: readonly Layer[],
	copyId: string,
	originalId: string | undefined
): readonly Layer[] {
	if (originalId === undefined) return layers;
	const at = layers.findIndex((layer) => layer.id === originalId);
	// `moveLayer` takes the copy out of the stack first, so the original slides up one and the index
	// the original holds *now* is the place immediately under it once the copy is put back.
	return at === -1 ? layers : moveLayer(layers, copyId, at);
}

// ── The Alignment question ────────────────────────────────────────────────────────────────────

/** One side of a contested Alignment, as the question shows it. */
export interface AlignmentSide {
	readonly controlPoints: number;
	/** When that version was last written, or `null` where neither side's evidence says. */
	readonly at: Date | null;
}

/** A contested Alignment, with everything the author needs to answer without opening both. */
export interface AlignmentQuestion {
	readonly imageId: string;
	readonly path: string;
	readonly mine: AlignmentSide;
	readonly theirs: AlignmentSide;
}

/** Which Alignment to keep. There is no third answer and there is no merge. */
export type AlignmentChoice = 'keep-mine' | 'take-theirs';

export interface AlignmentQuestionsOptions {
	readonly contested: readonly ContestedAlignment[];
	readonly store: ProjectStore;
	readonly readRemote: (path: string) => Promise<Bytes>;
	/** When the Remote's version was committed, or `null`. One date for every contested Alignment. */
	readonly remoteAt?: Date | null;
}

/**
 * Read both sides of every contested Alignment, for the question the author answers.
 *
 * ⚠ **A count of Control Points and a date, and nothing that could be mistaken for a preview.** The
 * two Alignments are of one sheet and differ by pixels; a rendering of each would look identical and
 * would invite an answer taken from a picture that cannot show the difference.
 *
 * ⚠ **Never throws.** A side that cannot be read is a count of nought and no date rather than a
 * refusal: the rest of the Sync does not stop for this question, so neither may reading it.
 */
export async function readAlignmentQuestions(
	options: AlignmentQuestionsOptions
): Promise<readonly AlignmentQuestion[]> {
	const questions: AlignmentQuestion[] = [];
	for (const contested of options.contested) {
		questions.push({
			imageId: contested.imageId,
			path: contested.path,
			mine: {
				controlPoints: countControlPoints(
					await read(() => options.store.read(contested.path as StorePath)),
					contested.imageId
				),
				at: await modifiedAt(options.store, contested.path)
			},
			theirs: {
				controlPoints: countControlPoints(
					await read(() => options.readRemote(contested.path)),
					contested.imageId
				),
				at: options.remoteAt ?? null
			}
		});
	}
	return questions;
}

const read = async (bytes: () => Promise<Bytes>): Promise<Bytes | null> =>
	bytes().catch(() => null);

/**
 * How many Control Points an Alignment document carries, or nought when it cannot be read.
 *
 * `parseAlignment` is the one reader, so a document another tool wrote counts the same way here as
 * it does everywhere else the app looks at one.
 */
function countControlPoints(bytes: Bytes | null, imageId: string): number {
	if (bytes === null) return 0;
	let alignment: Alignment;
	try {
		alignment = parseAlignment(bytes, { imageId });
	} catch {
		return 0;
	}
	return alignment.controlPoints.length;
}

/** When the Workspace last wrote a path, where its backing keeps that and `null` where it does not. */
async function modifiedAt(store: ProjectStore, path: string): Promise<Date | null> {
	const at = await store.modifiedAt?.(path as StorePath).catch(() => null);
	return typeof at === 'number' ? new Date(at) : null;
}

export interface ContestedAlignmentsOptions {
	readonly remote: RemoteRelationship;
	/** The commit to read the Remote's side at, or `null` to read the branch. */
	readonly commit: string | null;
	/** The plan's contested rows; the Alignments among them are the ones asked about. */
	readonly conflicts: readonly SourcePath[];
	readonly fetch?: FetchFn;
}

/**
 * The Alignment questions a plan raises, read from both sides.
 *
 * ⚠ **It downloads exactly the contested Alignments and nothing else.** There is one per Map Image
 * and they are small; a plan that fetched anything more would stop being a forecast.
 *
 * ⚠ **One date for GitHub's whole side, and it is the commit's.** A tree listing carries no dates at
 * all, so the only thing GitHub will say about when a file was last touched without a request per
 * file is when the state being read was committed. `null` where it would not say even that.
 */
export async function readContestedAlignments(
	store: ProjectStore,
	options: ContestedAlignmentsOptions
): Promise<readonly AlignmentQuestion[]> {
	const contested = classifyConflicts(
		options.conflicts.filter((row) => row.remote !== null).map((row) => row.path)
	).alignments;
	if (contested.length === 0) return [];

	const ref = options.commit ?? options.remote.branch;
	const source = createHttpProjectStore({
		resolve: (path) =>
			`${GITHUB_RAW_ORIGIN}/${urlPath(options.remote.owner)}/${urlPath(options.remote.repository)}/` +
			`${urlPath(ref)}/${urlPath(path)}`,
		...(options.fetch === undefined ? {} : { fetch: options.fetch })
	});
	return readAlignmentQuestions({
		contested,
		store,
		readRemote: (path) => source.read(path as StorePath),
		remoteAt:
			options.commit === null
				? null
				: await readRemoteCommitDate(options.remote, options.commit, options.fetch)
	});
}
