import { svelte } from '@sveltejs/vite-plugin-svelte';
import { defineConfig } from 'vitest/config';

// Seam 3 — one component rendered against props, in Node, against a DOM implementation.
//
// ═════════════════════════════════════════════════════════════════════════════════════════════
// WHY THE SEAM HAS A HOME HERE AND NOT ONLY IN `apps/editor`
//
// A component shared by both apps and tested from the app it used to live in is tested *through a
// consumer*: the second consumer is then either untested or carrying a copy of the same claim. So
// the harness moves with the component. `apps/editor/vitest.config.ts` is the prior art and its
// header carries the full argument for this seam — what a DOM implementation was probed for, what
// it gets wrong, and which claims therefore stay in `e2e/`. All of it applies here unchanged; the
// two ⚠ entries worth restating are that **nothing here may assert on `renderDescription`'s
// output** (DOMPurify answers "supported" against happy-dom and then returns its input essentially
// untouched) and that there is **no layout, no paint and no real hit testing**, so any claim about
// width, colour or reachability belongs to `e2e/`.
//
// ─────────────────────────────────────────────────────────────────────────────────────────
// ⚠ `resolve.conditions` IS NOT TUNING. WITHOUT IT NOTHING IN THIS PROJECT RUNS.
//
// Spelled at the top level, as `apps/editor`'s `editor-dom` project spells it and for the same
// measured reason: under `environment: 'happy-dom'` vitest transforms in vite's **`client`**
// environment, so `@sveltejs/vite-plugin-svelte` already sees `consumer: 'client'` and compiles
// components to `svelte/internal/client` with nothing asked of it. What is not free is how
// `svelte`'s own public modules resolve — its export map is `worker` / `browser` / `default`, and
// without this line `import { mount } from 'svelte'` gets the server build, which throws
// `mount(...) is not available on the server`.
//
// The list *replaces* vite's defaults rather than adding to them, so `browser` alone would drop
// `module` and the dev/prod condition and resolve other packages wrongly.
//
// **There is deliberately no `$lib` alias and no `$app/paths` stub here**, which is the one place
// this config differs from the editor's. Those are SvelteKit's, generated by an app's build, and a
// module in this package that reached for either would be reaching back into a consumer — which is
// exactly what `scripts/check-ui-package-imports.mjs` refuses. If a component moved here needs one,
// the import is the defect and the alias would be the workaround.
export default defineConfig({
	plugins: [svelte()],
	resolve: { conditions: ['module', 'browser', 'development|production'] },
	test: {
		name: 'ui',
		environment: 'happy-dom',
		// Every test in the package, not only the `.dom.test.ts` ones: a plain `.test.ts` moved here
		// with a component would otherwise be uncollected — not skipped and not reported, just absent
		// from a green run. A pure test costs nothing extra under happy-dom.
		include: ['src/**/*.test.ts'],
		expect: { requireAssertions: true },
		// No test may reach the network (CONTRIBUTING, "Five rules the toolchain enforces for you").
		// One implementation, imported from `core`, never a copy.
		setupFiles: [
			'@ballastella/core/test-fence',
			'./vitest-setup/dom-matchers.ts',
			// happy-dom implements no Web Animations API, and Svelte drives every `transition:` with a
			// duration through one. See the file's header for what it is and what it is not evidence of.
			'./vitest-setup/web-animations.ts'
		]
	}
});
